### ISSUE TITLE
Issue :  Cannot work on test data.

### ISSUE THREAD

**Issue by arita37** [shaypal5/pdpipe#11]
Column : country; 200 countries
train data :  2000 samples.
test data:  3 samples

If you have the same pipeline (ie oneHotEnCoder),  it will fail on test data,
because lack of samples.

I have developed a more advanced pipeline which solves this issue....

**Comment by shaypal5** [comment]
Actually, the OneHotEncode pipeline stage deals well with "train" and "test" data - more accurately, pre-fit and post-fit data - of very different sizes.

As you can see in the file containing the tests for this pipeline stage, both cases are tested:
https://github.com/shaypal5/pdpipe/blob/master/tests/col_generation/test_onehotencode.py

I'm closing this so you can reopen with a concrete example that reproduces the problem (and only then, please).
Let's get it to reproduce before we move to more advanced pipelines.

Cheers!
